//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : dp
//  @ File Name : CarTyre.java
//  @ Date : 15/08/2017
//  @ Author : 
//
//
package abstractfactory;


class CarTyre implements Tyre {
	
	@Override
	public void design() {
		System.out.println("Designing Car Tyre");
	}
	
	@Override
	public void manufacture() {
		System.out.println("Manufacturing Car Tyre");
	}
	
}
