//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : dp
//  @ File Name : TruckTyre.java
//  @ Date : 15/08/2017
//  @ Author : 
//
//
package abstractfactory;


class TruckTyre implements Tyre {
	
	@Override
	public void design() {
		System.out.println("Designing Truck Tyre");
	}
	
	@Override
	public void manufacture() {
		System.out.println("Manufacturing Truck Tyre");
	}
}
