//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : dp
//  @ File Name : Tyre.java
//  @ Date : 15/08/2017
//  @ Author : 
//
//
package abstractfactory;


public interface Tyre {
	
	public void design();
	public void manufacture();
	
}
